/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.awt.Color;
import java.sql.SQLException;
import java.util.List;

import javax.swing.JOptionPane;

import runner.Main;
import entities.ItemOrcamento;
import entities.OrdemDeServico;
import entities.OrdemDeServico.STATUS;

/**
 *
 * @author ThiagoLucas
 */
public class Orcamento extends javax.swing.JFrame {
	
	OrdemDeServico os = Main.getCurrentOS();
	List<ItemOrcamento> listaItems;
	Object listaItemsMatrix[][] = new Object[10][3];

    /**
     * Creates new form Orcamento
     */
    public Orcamento() {
    	
    	listaItems = Main.itemOrcamentoDao.findAllItemsFromOS(os);
        for (int i = 0; i < listaItems.size(); i++) {
        	listaItemsMatrix[i][0] = listaItems.get(i).getDescricao();
        	listaItemsMatrix[i][1] = listaItems.get(i).getValorUnitario();
        	listaItemsMatrix[i][2] = listaItems.get(i).getQuantidade();
		}
    	
        initComponents();
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Orçamento");

        jTable1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        		listaItemsMatrix,
            new String [] {
                "Item", "Valor", "Quantidade"
            }
        ));
        jTable1.setRowHeight(40);
        jTable1.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButton1.setText("Salvar Orçamento");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(346, 346, 346)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(368, 368, 368)
                                .addComponent(jLabel1)))
                        .addGap(0, 282, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orcamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orcamento().setVisible(true);
            }
        });
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    	int initialItemsSize = listaItems.size();
    	for (int i = 0; i < listaItemsMatrix.length; i++) {
    		String desc = (String) jTable1.getValueAt(i, 0);
    		Double valor;
    		Double quant;
    		
    		try {
    			// Caso ja seja um double
    			valor = (Double) jTable1.getValueAt(i, 1);
        		quant = (Double) jTable1.getValueAt(i, 2);
			} catch (Exception e) {
				//Caso seja String				
				valor = Double.valueOf((String) jTable1.getModel().getValueAt(i, 1));
				quant = Double.valueOf((String) jTable1.getModel().getValueAt(i, 1));
			}

    		if (desc == null && valor == null && quant == null){
    			continue;
    		}
    		if (i < initialItemsSize){
    			listaItems.get(i).setDescricao(desc);
    			listaItems.get(i).setValorUnitario(valor);
    			listaItems.get(i).setQuantidade(quant);
    		} else {
				ItemOrcamento item = new ItemOrcamento();
				item.setDescricao(desc);
				item.setValorUnitario(valor);
				item.setQuantidade(quant);
				item.setOrdemDeServico(os);
				listaItems.add(item);
			}
		}
    	try {
    		Main.itemOrcamentoDao.createOrUpdateItems(listaItems);
    		os.setStatus(STATUS.AGUARDANDO_APROVACAO.ordinal());
			Main.ordemdeservicoDao.update(os);
			JOptionPane.showMessageDialog(null, "O orcamento foi enviado para aprovacao do cliente");
		} catch (SQLException e) {
			JOptionPane.showMessageDialog(null, "Ocorreu um erro ao atualizar");
			e.printStackTrace();
		}
    	
        this.setVisible(false);
        new DetalhesOSTecnico().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
